export default {
	"pages": {
		"root": {
			"id": "root",
			"pageUrl": "root",
			"name": "root",
			"children": [
				"661c7265e8900d0022f1822c",
				"661c7265e8900d0022f1822f",
				"6620819d1d712a0023330b70",
				"662082b8f0cb1d0025f49150"
			]
		},
		"661c7265e8900d0022f1822c": {
			"id": "661c7265e8900d0022f1822c",
			"name": "404",
			"pageUrl": "404"
		},
		"661c7265e8900d0022f1822f": {
			"id": "661c7265e8900d0022f1822f",
			"name": "index",
			"pageUrl": "index",
			"seo": {
				"favicon_32px": "https://uploads.quarkly.io/661c7265e8900d0022f18227/images/fusion%20audio.png?v=2024-04-15T00:52:41.142Z",
				"favicon_apple_152px": "https://uploads.quarkly.io/661c7265e8900d0022f18227/images/fusion%20audio.png?v=2024-04-15T00:52:41.142Z",
				"favicon_win10_270px": "https://uploads.quarkly.io/661c7265e8900d0022f18227/images/fusion%20audio.png?v=2024-04-15T00:52:41.142Z",
				"title": "Fusion Audio Distribution",
				"description": "A free music distribution service that can deliver in as little as 3 days"
			}
		},
		"6620819d1d712a0023330b70": {
			"id": "6620819d1d712a0023330b70",
			"pageUrl": "tos",
			"name": "TOS"
		},
		"662082b8f0cb1d0025f49150": {
			"id": "662082b8f0cb1d0025f49150",
			"pageUrl": "privacy-policy",
			"name": "Privacy Policy"
		}
	},
	"mode": "production",
	"projectType": "gatsby",
	"site": {
		"styles": {},
		"seo": {
			"title": "Fusion Audio Distribution",
			"customSitemapDomain": "https://fusion.l5.ca",
			"description": "A fast and reliable music distributor for all artists new or experienced. Submit the form to get started on your journey!",
			"robotsFileType": "autogenerated",
			"sitemapFileType": "autogenerated",
			"og:title": "Fusion Audio Distribution",
			"og:description": "A fast and reliable music distributor for all artists new or experienced. Submit the form to get started on your journey!",
			"og:image": "https://uploads.quarkly.io/661c7265e8900d0022f18227/images/android-chrome-512x512.png?v=2024-04-15T02:25:23.709Z"
		}
	}
}